[package]
name = "sqlite3_mini"
version = "0.1.0"
authors = ["yonemotot <takuro100881@ezweb.ne.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlite3 = "0.24.0"